### ISSUE TITLE
(style/text) добавить универсальные стили для блока Text

### ISSUE THREAD

**Issue by pomazkovanton** [pomazkovanton/noiceland#1]
![Image](https://user-images.githubusercontent.com/18042030/219688868-db2d442b-bc35-47f7-9b05-8f0f94eaa10a.png)

  -  Стили создать в каталоге src/components/UI/text
  -  В данной папке дополнительно создать файл text.html со всеми возможными примерами испоьзования компонента
  -  Компонент может быть как текстом, так и заголовком 
  -  Убрать всю внешнию геометрию и ширину сделать чтобы растягивалась на всю ширину родительского компонента

**Comment by arctikbear** [comment]
@pomazkovanton не могу закоммитить, насколько я понял, husky не нравятся правила именования


![Image](https://user-images.githubusercontent.com/11219356/219899759-36164efd-9c5a-42e1-83d2-1bdd1b709b66.png)

**Comment by arctikbear** [comment]
вот, что получилось со шрифтами:


![Image](https://user-images.githubusercontent.com/11219356/219899853-428fd5b8-64a1-431b-9673-0f53794651e2.png)

**Comment by pomazkovanton** [comment]
{
  "extends": ["stylelint-config-standard", "stylelint-config-prettier", "stylelint-config-clean-order"],
  "plugins": ["stylelint-order"],
  "rules": {
    "selector-class-pattern": null
  }
}

**Comment by arctikbear** [comment]
пришлось проверку наименования переменных тоже выключить из правил:
`  "rules": {
    "selector-class-pattern": null,
    "custom-property-pattern": null
  }`
