### ISSUE TITLE
(fix/folders) переместить все изображения в папку assets

### ISSUE THREAD

**Issue by arctikbear** [pomazkovanton/noiceland#21]
Переместить папку images из accets в assets, папку accets удалить. Проверить импорты.

![Image](https://user-images.githubusercontent.com/11219356/219866932-8181a970-57fb-4385-aa96-37fed6621f27.png)

**Comment by P1xelST** [comment]
Имба!! Мне прям это все так нарвиться! : ) очень круто :D )
