### ISSUE TITLE
(style/button) создать стили для кнопок

### ISSUE THREAD

**Issue by pomazkovanton** [pomazkovanton/noiceland#7]
![Image](https://user-images.githubusercontent.com/18042030/219766340-4045d799-6669-4352-8c59-3dfb5db608e0.png)

  -  Стили создать в каталоге src/components/UI/button
  -  В данной папке дополнительно создать файл button.html со всеми возможными примерами испоьзования компонента
  -  Компонент может быть как ссылкой, так и кнопкой
  -  Убрать всю внешнию геометрию и ширину сделать чтобы растягивалась на всю ширину родительского компонента

**Comment by AlexeyKrutiakov** [comment]
@pomazkovanton

- не совсем понятно, что значит убрать всю внешнюю геометрию? убрать border?
- то, что компонент может быть и ссылкой и кнопкой не понятно как нужно реализовать. имя блока по БЭМ button. или имя не имеет значения? имеется ввиду, что тэг может быть и <button> и <a> ? если так, то достаточно показать работу компонента в примере использования в файле button.html?

**Comment by pomazkovanton** [comment]
- Убрать ограничение ширины и внешние отступы  (margin)
- когда пишешь код или разметку лучше использовать кавычки тройные которые (ё), чтобы код отображался в комментарии
- да, я имею ввиду что может быть как ```<a>``` так и ```<button>```
